name: CI/CD - Build, Scan, Push Docker Image, Update YAML

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  IMAGE_NAME: suchithra05/vote-app

jobs:
  build:
    name: Build, Scan, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} ./apps

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@0.11.2
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: table
          exit-code: 0  # Fails pipeline if vulnerabilities found
          severity: CRITICAL,HIGH

      - name: Push Docker Image
        run: docker push $IMAGE_NAME:${{ github.sha }}

  deploy:
    name: Update Kubernetes YAML
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update image tag in YAML
        run: |
          sed -i "s|\(image: $IMAGE_NAME:\).*|\1${{ github.sha }}|" k8s-manifests/flask-vote.yaml
          cat k8s-manifests/flask-vote.yaml

      - name: Set Git identity and push changes
        run: |
          git config --global user.email "suchithraee1999@gmail.com"
          git config --global user.name "suchithra05"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add k8s-manifests/flask-vote.yaml
          git diff --cached --quiet || git commit -m "Update image tag to ${{ github.sha }}"
          git push
