name: CI/CD - Build and Push Docker Image, Update YAML

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: suchithra05/vote-app

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image to Docker Hub
      run: |
        docker build -t $IMAGE_NAME:${{ github.sha }} ./apps
        docker push $IMAGE_NAME:${{ github.sha }}

    deploy:
    name: Update YAML with New Image Tag
    runs-on: ubuntu-latest
    needs: build  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

   
    - name: Pull image from Docker Hub
      run: docker pull $IMAGE_NAME:${{ github.sha }}

    - name: Update image tag in YAML
      run: |
        sed -i "s|\(image: $IMAGE_NAME:\).*|\1${{ github.sha }}|" k8s-manifests/flask-vote.yaml
        cat k8s-manifests/flask-vote.yaml  # Debug step

    - name: Commit and Push Updated Manifest
      run: |
        git config --global user.email "suchithraee1999@gmail.com"
        git config --global user.name "suchithra05"
        git add k8s-manifests/flask-vote.yaml
        git diff --cached --quiet || git commit -m "Update image tag to ${{ github.sha }}"
        git push
