name: CI - Build, Scan

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

env:
  IMAGE_NAME: vote-app
  IMAGE_TAG: ${{ github.event.pull_request.head_sha || github.sha }}
  ARTIFACTORY_REGISTRY: trial1e0fhi.jfrog.io/docker-local

jobs:
  build:
    name: 🏗️ Build & Push to Artifactory
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Artifactory
        run: |
          echo "${{ secrets.ARTIFACTORY_PASSWORD }}" | docker login $ARTIFACTORY_REGISTRY -u ${{ secrets.ARTIFACTORY_USERNAME }} --password-stdin

      - name: Build & Push Docker image
        run: |
          docker build -t $ARTIFACTORY_REGISTRY/$IMAGE_NAME:$IMAGE_TAG ./apps
          docker push $ARTIFACTORY_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

  scan:
    name: 🔍 Pull & Scan from Artifactory
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Log in to Artifactory
        run: |
          echo "${{ secrets.ARTIFACTORY_PASSWORD }}" | docker login $ARTIFACTORY_REGISTRY -u ${{ secrets.ARTIFACTORY_USERNAME }} --password-stdin

      - name: Pull image from Artifactory
        run: docker pull $ARTIFACTORY_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@0.11.2
        with:
          image-ref: ${{ env.ARTIFACTORY_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH
