name: CI - Build, Scan, Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  IMAGE_NAME: suchithra05/vote-app

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.set_tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image tag
        id: set_tag
        run: echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ steps.set_tag.outputs.tag }} ./apps

  scan:
    name: Scan Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.11.2
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ needs.build.outputs.image_tag }}
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

  push:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: scan

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push $IMAGE_NAME:${{ needs.scan.needs.build.outputs.image_tag }}

      - name: Trigger CD in manifests repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: suchithra05/vote-app-manifests
          event-type: deploy-trigger
          client-payload: |
            {
              "image_tag": "${{ github.sha }}"
            }
