name: 🚀 Push to Docker Hub & Trigger CD

on:
  workflow_run:
    workflows: ["CI - Build, Scan"]
    types:
      - completed

  workflow_dispatch:  # Enables manual run button

permissions:
  contents: read

env:
  IMAGE_NAME: vote-app
  IMAGE_TAG: ${{ github.event.pull_request.head_sha || github.sha }}
  ARTIFACTORY_REGISTRY: trial1e0fhi.jfrog.io/docker-local
  DOCKERHUB_REGISTRY: docker.io

jobs:
  push-and-trigger:
    name: 🚀 Push to Docker Hub & Trigger CD
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Artifactory
        run: |
          echo "${{ secrets.ARTIFACTORY_PASSWORD }}" | docker login $ARTIFACTORY_REGISTRY -u ${{ secrets.ARTIFACTORY_USERNAME }} --password-stdin

      - name: Pull image from Artifactory
        run: docker pull $ARTIFACTORY_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Tag for Docker Hub
        run: |
          docker tag $ARTIFACTORY_REGISTRY/$IMAGE_NAME:$IMAGE_TAG $DOCKERHUB_REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: |
          docker push $DOCKERHUB_REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG

      - name: Trigger CD Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: suchithra05/voteapp-manifests
          event-type: deploy-trigger
          client-payload: |
            {
              "image_tag": "${{ env.IMAGE_TAG }}"
            }
