name: Trigger CD on PR Merge to Dev

on:
  pull_request:
    types: [closed]
    branches:
      - dev

permissions:
  contents: read
  actions: write

jobs:
  trigger-cd:
    if: github.event.pull_request.merged == true
    name: Trigger CD Workflow in Manifests Repo
    runs-on: ubuntu-latest

    steps:
      - name: Send Dispatch Event to CD Repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: suchithra05/voteapp-manifests
          event-type: deploy-trigger
          client-payload: >-
            {
              "image_tag": "${{ github.sha }}",
              "target_branch": "dev"
            }
