name: CD - Push to Docker Hub & Trigger ArgoCD pipeline

on:
  workflow_run:
    workflows: ["CI - Build, Scan."]
    types:
      - completed

jobs:
  deploy:
    name: Deploy After Merge
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'dev' }}
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: vote-app
      IMAGE_TAG: ${{ github.sha }}
      ARTIFACTORY_REGISTRY: trial1e0fhi.jfrog.io/docker-local
      DOCKERHUB_REGISTRY: docker.io

    steps:
      - name: Log in to Artifactory
        run: echo "${{ secrets.ARTIFACTORY_PASSWORD }}" | docker login $ARTIFACTORY_REGISTRY -u ${{ secrets.ARTIFACTORY_USERNAME }} --password-stdin

      - name: Pull image
        run: docker pull $ARTIFACTORY_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Tag image for Docker Hub
        run: docker tag $ARTIFACTORY_REGISTRY/$IMAGE_NAME:$IMAGE_TAG $DOCKERHUB_REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: docker push $DOCKERHUB_REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG

      - name: Trigger ArgoCD CD Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: suchithra05/voteapp-manifests
          event-type: deploy-trigger
          client-payload: |
            {
              "image_tag": "${{ env.IMAGE_TAG }}"
            }
